export const ReportesApis = {
  catalogo: '/api/CatReportes/sp_cat_reportesSel2',
  sucursales: '/api/CatSucursales/sp_bw_cat_sucursales_sel',
  estilistas: '/api/CatReportes/sp_pos_estilistas_listado',
  marcas: '/api/CatReportes/sp_bw_cat_marcas_sel',
  familiasMarca: '/api/CatReportes/sp_bw_cat_marcasfamilias_sel',
  areas: '/api/CatReportes/sp_bw_cat_areas_sel',
  productos: '/api/CatReportes/sp_bw_cat_productos_sel',
  proveedores: '/api/CatReportes/sp_bw_cat_combo_proveedores',
  mediosPagos: '/api/CatReportes/sp_reporte_medios_pagos',
  mediosPagosFolios: '/api/CatReportes/sp_reporte_medios_pagos_folios',
  clientesAtendidosPeriodo: '/api/CatReportes/sp_reporte_clientes_atendidos_periodo',
  visitas: '/api/CatReportes/sp_reporte_visitas',
  saldoPuntos: '/api/CatReportes/sp_reporte_saldo_puntos',
  inventario: '/api/CatReportes/sp_reporte_inventario',
  ajusteInventario: '/api/CatReportes/sp_reporte_ajuste_inventario',
  traspasosSucursales: '/api/CatReportes/sp_reporte_traspasos_sucursales',
  inventarioCompras: '/api/CatReportes/sp_reporte_inventario_compras',
  inventarioErp: '/api/CatReportes/sp_reporte_inventario_ERP',
  rentabilidadInsumos: '/api/CatReportes/sp_reporte_rentabilidad_insumos',
};
