export type Cliente = {
  noCliente: string
  nombre: string
  apPaterno: string
  apMaterno: string
  domicilio: string
  calle: string
  numExterior: string
  numInterior: string
  ciudad: string
  municipio: string
  estado: string
  colonia: string
  cp: string
  rfc: string
  curp: string
  telefono: string
  fax: string
  email: string
  contacto: string
  nombreFiscal: string
  limiteCredito: number
  fechaAlta: Date
  personaFisica: boolean
  mayoreo: boolean
  diasCredito: number
  suspendido: boolean
  sucursalOrigen: number
  especial: boolean
  plus: boolean
  version: string
  fechaAct: Date
  listaPrecioEspecial: number
  claveListaCredito: number
  claveListaMayoreo: number
  cuentaContable: string
  referencias: string
  clavePuntos: string
  numPlastico: string
  sucAsigPlast: number
  fechaAsigPlast: Date
  usrAsigPlast: string
  plasticoActivo: boolean
  genero: string
  fechaNac: Date
  correoFactura: string
  contrasena: string
  noInfoAm: boolean
  regimenFiscal: string
  claveRegistroMovil: string
}