

export const routes = {
  login: "/login",
  home: "/",
  mainMenu: "/",
  demo: "/demo",
  demoStepper: "/demoStepper",
  generadorFormularios: "/generadorFormularios",
  recepcion: "/recepcion",
  catalogos: "/catalogos",
  cat_Areas: "/cat_Areas",
  cat_Tipo_Descuento: "/cat_Tipo_Descuento",
  cat_Compradores: "/cat_Compradores",
  cat_Sucursales: "/cat_Sucursales",
  cat_Productos: "/cat_Productos",
  cat_act_Precios_grupo: "/cat_act_Precios_grupo",
  cat_metaempleados: "/cat_metaempleados",
  cat_metasucursal: "/cat_metasucursal",
  cat_configcomisiones: "/cat_configcomisiones",
  cat_configcomisiones2: "/cat_configcomisiones2",
  cat_accesosalternos: "/cat_accesosalternos",
  cat_conceptos_ajustes: "/cat_conceptos_ajustes",
  cat_tipos_movimientos: "/cat_tipos_movimientos",
  cat_nominas_movimientos: "/cat_nominas_movimientos",
  cat_dias_festivos: "/cat_dias_festivos",
  cat_niveles_estudios_rrhh: "/cat_niveles_estudios_rrhh",
  cat_nominas_horarios: "/cat_nominas_horarios",
  cat_cuentas_bancarias: "/cat_cuentas_bancarias",
  cat_tipos_cuentas: "/cat_tipos_cuentas",
  cat_usuarios: "/cat_usuarios",
  cat_nominas_folios: "/cat_nominas_folios",
  Cat_turnos_dobles: "/Cat_turnos_dobles",
  cat_perfiles_permisos: "/cat_perfiles_permisos",
  pos: "/pos",

  //Catalogos
  cat_clientes_form: "/cat_Clientes_form",
  cat_Proveedores: "/cat_proveedores",
  cat_Clientes: "/cat_clientes",
  cat_Marcas: "/cat_marcas",
  AsignacionHorarios: "/asignacionhorarios",
  Cat_Marcas_Familias: "/cat_marcas_familias",
  modulo_servicios_insumos: "/modulo_servicios_insumos",
  modulo_porcentajes_puntos: "/modulo_porcentajes_puntos",
  cat_AreasDeptosClases:"/cat_AreasDeptosClases",
  retiros: "/retiros",
  corte_parcial: "/corte-parcial",
  corte_dia: "/corte-dia",
  config_promociones_descuento_porcentual: "/config_promociones_descuento_porcentual",
  cat_Plasticos_Autorizados: "/cat_Plasticos_Autorizados",
  factores_sucursal: "/factores_sucursal",
  cat_Medios_Pago: "/cat_medios_pago",
  cat_DescProveedores: "/cat_DescProveedores",
  cat_Proveedores_Acreedores: "/cat_proveedores_acreedores",
  cat_Trabajadores: "/cat_trabajadores",
  cat_nomina_departamentos: "/cat_nomina_departamentos",
  cat_nomina_Status: "/cat_nomina_Status",
  cat_nomina_formas_pagos: "/cat_nomina_formas_pagos",
  cat_nomina_puestos: "/cat_nomina_puestos",
  cat_nomina_bajas: "/cat_nomina_bajas",
  cat_Categorias: "/cat_Categorias",
  cat_PermisosDeptos:"/cat_PermisosDeptos",
  Validacion_Productos_Servicios: "/validacion_productos_servicios",
  pos2: "/pos2",
  carteleraDigital: "/cartelera-digital",
  facturacion: "/facturacion",
  inventario: "/inventario",
  traspasoMercancia: "/traspaso-mercancia",
};

