

export const routes = {
  login: "/login",
  home: "/",
  mainMenu: "/",
  demo: "/demo",
  demoStepper: "/demoStepper",
  generadorFormularios: "/generadorFormularios",
  recepcion: "/recepcion",
  catalogos: "/catalogos",
  cat_Areas: "/cat_Areas",
  cat_Tipo_Descuento: "/cat_Tipo_Descuento",
  cat_Compradores: "/cat_Compradores",
  cat_Sucursales: "/cat_Sucursales",
  cat_Productos: "/cat_Productos",
  cat_act_Precios_grupo: "/cat_act_Precios_grupo",
  cat_metaempleados: "/cat_metaempleados",
  cat_metasucursal: "/cat_metasucursal",
  cat_configcomisiones: "/cat_configcomisiones",
  cat_configcomisiones2: "/cat_configcomisiones2",
  cat_accesosalternos: "/cat_accesosalternos",
  cat_conceptos_ajustes: "/cat_conceptos_ajustes",
  cat_tipos_movimientos: "/cat_tipos_movimientos",
  cat_nominas_movimientos: "/cat_nominas_movimientos",
  cat_dias_festivos: "/cat_dias_festivos",
  cat_niveles_estudios_rrhh: "/cat_niveles_estudios_rrhh",
  cat_nominas_horarios: "/cat_nominas_horarios",
  cat_cuentas_bancarias: "/cat_cuentas_bancarias",
  cat_tipos_cuentas: "/cat_tipos_cuentas",
  cat_usuarios: "/cat_usuarios",
  cat_nominas_folios: "/cat_nominas_folios",
  pos: "/pos",

  //Catalogos
  cat_clientes_form: "/cat_Clientes_form",
  cat_Proveedores: "/cat_proveedores",
  cat_Clientes: "/cat_clientes",
  cat_Marcas: "/cat_marcas",
  AsignacionHorarios: "/asignacion_horarios",
  Cat_Marcas_Familias: "/cat_marcas_familias",
  modulo_servicios_insumos: "/modulo_servicios_insumos",
  modulo_porcentajes_puntos: "/modulo_porcentajes_puntos",
  retiros: "/retiros",
  corte_parcial: "/corte-parcial",
  corte_dia: "/corte-dia",

};

